choco install vscode -y
choco install notepadplusplus -y
choco install git -y
choco install nodejs-lts -y
choco install python -y 
choco install brave -y
choco install googlechrome -y
choco install keepass.install -y
choco install spotify -y
choco install notion -y
choco install heroku-cli -y
choco install nano -y
choco install lazygit -y
